[package]
name = "frame-benchmarking-pallet-pov"
version = "18.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Pallet for testing FRAME PoV benchmarking"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
frame-benchmarking = { workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"]}
scale-info = { features = ["derive"], workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"scale-info/std",
	"frame/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
]
