[package]
name = "frame-benchmarking"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Macro for benchmarking a FRAME runtime."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"]}
# frame-support = { workspace = true }
frame-support-procedural = { workspace = true }
# frame-system = { workspace = true }
linregress = { optional = true, workspace = true }
log = { workspace = true }
paste = { workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }
serde = { optional = true, workspace = true, default-features = true }
sp-runtime-interface = { workspace = true }
static_assertions = { workspace = true, default-features = true }

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
rusty-fork = { workspace = true }
sc-client-db = { workspace = true }
sp-externalities = { workspace = true }
sp-keystore = { workspace = true, default-features = true }
sp-state-machine = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"frame-support-procedural/std",
	"linregress",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-externalities/std",
	"sp-keystore/std",
	"sp-runtime-interface/std",
	"sp-state-machine/std",
]
runtime-benchmarks = [
	"sc-client-db/runtime-benchmarks",
]
