[package]
name = "pallet-remark"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Remark storage pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
frame = { workspace = true, features = ["runtime"] }
scale-info = { features = ["derive"], workspace = true }
serde = { optional = true, workspace = true, default-features = true }

[dev-dependencies]
sp-core = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame/std",
	"scale-info/std",
	"serde",
]
try-runtime = [
	"frame/try-runtime",
]
