[package]
name = "frame-metadata-hash-extension"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME signed extension for verifying the metadata hash"

[dependencies]
array-bytes = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"]}
const-hex = { workspace = true }
docify = { workspace = true }
log = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }

[dev-dependencies]
frame-metadata = { features = ["current", "unstable"], workspace = true, default-features = true }
merkleized-metadata = { workspace = true }
sp-tracing = { workspace = true, default-features = true }
sp-transaction-pool = { workspace = true, default-features = true }
substrate-test-runtime-client = { workspace = true }
substrate-wasm-builder = { features = ["metadata-hash"], workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"const-hex/std",
	"log/std",
	"scale-info/std",
]
